### ISSUE TITLE
wfantund lifecycle

### ISSUE THREAD

**Issue by Stephen-Campbell-UTD** [Confucius19/utdesign-ti-wisunfan-webserver#2]
https://github.com/Stephen-Campbell-UTD/utdesign-ti-wisunfan-webserver/blob/5cc8aead0447a7192e1404b8923188f99ad2c7e4/src/index.js#L263

Something I noticed was that if you launch the server and then the server exits or errors out inexplicably there is a background wfantund process running. This is something I hadn't thought about too much.

This locks the /dev/ttyACM* forcing the user to manually kill wfantund if they want to use pyspinel or use another application with the ncp.

I propose that we should kill the wfantund process we started if the server exits or errors out and wfantund is still running.

**Comment by ghost** [comment]
Ahh gotcha, agreed.
